modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
logoFile="icon.png"
displayURL="https://www.curseforge.com/minecraft/mc-mods/sheep-consistency-unofficial-forge-port"
description="Makes the sheared variants of sheep match the colors they were dyed with. Based on bedrock version of sheep."

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.sheepconsistencyforge]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="CLIENT"
[[dependencies.sheepconsistencyforge]]
    modId="minecraft"
    type="required"
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="CLIENT"

[modproperties.sheepconsistencyforge]
    catalogueItemIcon="icon.png" #Support for Catalogue mod

